Params.PACMANCOUNT = 50;
Params.BIAS = -1;
Params.POPULATION = 50;
Params.MUTATION_RATE = 0.1;
Params.CROSS_RATE = 0.7;
Params.WEIGHT_COUNT = 14;
Params.PERTURBATION_RATE = 0.3;
Params.THRESHOLD = 0.5;
Params.ELITE_COUNT = 4;         //Number of "elite" genomes to sample from.
Params.ELITE_NUMBER = 1;        //Index of the "elite" ?